### ISSUE TITLE
Process和父进程共享一个连接池

### ISSUE THREAD

**Issue by JiankangMai** [swoft-cloud/swoft-framework#111]
```    
//Swoft\Process\ProcessBuilder.php
/**
     * After process
     *
     * @param string $processName
     * @param bool   $boot
     */
    private static function beforeProcess(string $processName, $boot)
    {
        if ($boot) {
            BeanFactory::reload();
            $initApplicationContext = new InitApplicationContext();
            $initApplicationContext->init();
        }

        App::trigger(ProcessEvent::BEFORE_PROCESS, null, $processName);
    }
````
boot 为false的Process,其和父进程共享一个连接池

**Comment by JiankangMai** [comment]
update了下framework，新版已经无法复现相关问题了

**Comment by JiankangMai** [comment]
see https://wiki.swoole.com/wiki/page/325.html

**Comment by inhere** [comment]
你是说这里有问题吗

**Comment by JiankangMai** [comment]
是的，我看了下代码，Procee本身没有机制重新加载链接池对象或者替换链接池对象中的现有connection对象。
目前对于boot为true的Procee,链接池对象会作为一个Bean随着整个Bean容器的重载而重载，
但是boot为false的情况，应该有响应的机制对对链接池这类特殊对象做相应的处理。

**Comment by inhere** [comment]
进程启动时因为一些问题，并没有初始化连接池的 是在第一次使用时初始化的

**Comment by JiankangMai** [comment]
举个例子,在启动Process之前，父进程已经进行了一堆crud操作了，这时连接池已经被初始化并生成了链接对象。如果现在父进程再启动一个boot=false的Process,那这个子进程就会继承父进程中的原有的ConnectionPool以及池中可用链接。

这时链接就被两个进程共享了，所以所以我觉得Process启动的时候如果连接池池已经存在了，应该至少要重置一下池内的SplQueue或Channel

**Comment by inhere** [comment]
这样子用的话确实会有这样的问题

**Comment by inhere** [comment]
move to https://github.com/swoft-cloud/swoft/issues/267
