### ISSUE TITLE
CoreBean 机制导致的无法使用注解的BUG

### ISSUE THREAD

**Issue by zcmzc** [swoft-cloud/swoft-framework#118]
CoreBean 配置
`public function beans()

    {
        return [
            SecretKeyInterface::class => [
                'class' => SecretKey::class
            ],
            EncryptHandlerInterface::class => [
                'class' => EncryptHandler::class
            ]
        ];
    }`
底层在实例化时 , 只注入了CoreBean 配置下的属性, 若无配置, 也不会触发类里的成员注解

**Comment by zcmzc** [comment]
简单点讲 , 在config/basebase.php 添加配置

    'IndexLogic'  => [
        'class' => \App\Models\Logic\IndexLogic::class,
    ],

在控制器分别通过类名和别名调用

    $indexLogic = App::getBean(IndexLogic::class);
    $indexLogic = App::getBean('IndexLogic');

通过别名调用的无法触发类里的注解

**Comment by inhere** [comment]
我先close 了, 1 里面 看情况是否支持别名。
2 会支持bean别名
