### ISSUE TITLE
配置文件未走别名

### ISSUE THREAD

**Issue by zcmzc** [swoft-cloud/swoft-framework#121]
'components' => [
        'custom' => [
            "Swoft\\Encrypt" => dirname(dirname(__DIR__)).'/vendor/zcmzc/swoft-encrypt/src/',
            'Swoft\\Blade' => dirname(dirname(__DIR__)).'/vendor/lldca/swoft-blade/src/Blade',
        ],
    ],
文件路径不能写别名`@vendor`

**Comment by zcmzc** [comment]
`CustomComponentsRegister` 下的`registerServerNamespace()` 方法修改

**Comment by limingxinleo** [comment]
好，我会尽快处理的

**Comment by limingxinleo** [comment]
@zcmzc 你可以直接配置成这样，是支持composer.json的配置的
~~~
'components' => [
    'custom' => [
        "Swoft\\Encrypt\\",
        'Swoft\\Blade\\',
    ],
],
~~~

**Comment by zcmzc** [comment]
666
