### ISSUE TITLE
被扫描目录的路径分隔符处理有问题

### ISSUE THREAD

**Issue by Veitor** [swoft-cloud/swoft-framework#124]
## 重现步骤

1. 在composer.json中定义一个自己的psr4加载名称，如
```json
[
    "autoload": {
       "psr-4": {
            "Foo\\": "src/"
        }
    }
]
```

2. 在`app/config/properties/app.php`中加入一个扫描路径，如
```php
return [
    'beanScan' => [
        'Foo\Bar\FooBar, //其代表了src/Bar/FooBar目录
    ]
];

```

3. 在`Swoft\Bean\Resource::addScanNamespace()`中，第2步中添加的`Foo\Bar\FooBar`命名空间将被在这方法内处理。具体的由`ComposerHelper::getDirByNamespace()`（200行）处理，但处理之后得到的`$nsPath`路径大致为`/var/www/swoft/vendor/composer/../../src\Foo\Bar\FooBar`，这是由于`getDirByNamespace()`方法中把第1步psr4中设置的前缀路径直接与第2步中子命名空间相拼接得到的。

4. 第3步得到了`/var/www/swoft/vendor/composer/../../src\Foo\Bar\FooBar`，这是一个实际存在的路径，但由于目录分隔符的问题，按理反斜杠`\`都应该被处理成`/`。但201行开始的代码只处理了`BASE_PATH`常量值下的路径，并没有对`ComposerHelper::getDirByNamespace()`返回的结果做处理。

5. 由于反斜杠的未处理，最终导致后续执行判断目录是否存在`is_dir()`时，返回了`false`

## 建议

对`Swoft\Bean\Resource::addScanNamespace()`做修改，统一处理`$nsPath`，把反斜杠处理掉

问题代码片段：
```php
 /**
     * @param array $namespaces
     */
    public function addScanNamespace(array $namespaces)
    {
        foreach ($namespaces as $key => $namespace) {
            if (is_string($key)) {
                $this->scanNamespaces[$key] = $namespace;
                continue;
            }
            $nsPath = ComposerHelper::getDirByNamespace($namespace);
            if (!$nsPath) {
                $nsPath = str_replace("\\", "/", $namespace);
                $nsPath = BASE_PATH . "/" . $nsPath;
            }
            $this->scanNamespaces[$namespace] = $nsPath;
        }
        $this->registerNamespace();
    }
```

**Comment by huangzhhui** [comment]
`beanScan` 配置在最新版内实际是已经没有使用场景了的，Swoft会自动扫描除掉`bootScan`所有 `App` 内的文件
