### ISSUE TITLE
Adapter\CoroutineAdapter 请求Https 时有bug

### ISSUE THREAD

**Issue by zcmzc** [swoft-cloud/swoft-framework#82]
Coroutine\Http\Client 构造方法第三个参数若请求Https 则必填true

**Comment by zcmzc** [comment]
![image](https://user-images.githubusercontent.com/28561563/35554904-495b8e00-05d8-11e8-8470-1b17e1b8fa55.png)

**Comment by huangzhhui** [comment]
Component 分支已修复

**Comment by huangzhhui** [comment]
component分支已经合并到master了
