### ISSUE TITLE
框架对顶级目录的父级目录下其他目录存在依赖

### ISSUE THREAD

**Issue by JiankangMai** [swoft-cloud/swoft-framework#93]
问题代码:
```
class WorkerAnnotationResource extends AnnotationResource
{
    /**
     * Register the scaned namespace
     */
    public function registerNamespace()
    {
        $swoftDir = \dirname(__FILE__, 5);
         //.....
    }
```
根据代码,，目测这个```dirname(__FILE__,5)```原意是指composer生成`vendor\swoft`目录。用于Swoft扫描该目录下所有swoft组件注册注解。
但是该目录获取方式较为脆弱，对swoft-framework所在目录存在隐形依赖。对于一般使用composer安装的应用不会有问题，但其他场景下可能会有微妙的问题。

已知问题场景：
1.  ```swoft-framework```,存放路径为```\WEB_ROOT\swoft-framework```
2.  在```\WEB_ROOT\```下执行```composer require   "eaglewu/swoole-ide-helper=dev-master"```。
3.  执行后相关目录为
```WEB_ROOT\swoft-framework\***```
```WEB_ROOT\swoole-ide-helper\****```
4.  执行phpunit或者composer test
5.  swoft会扫描一个理论上和项目外的swoole-ide-helper内的文件,间接导致在注解初始化阶段框架加载类```Swoole\Functionals```，从而导致Fatal Error(redeclare swoole_set_process_name())

问题解决优先级：低
主要影响对象:不使用容器的开发者

**Comment by huangzhhui** [comment]
有个疑问是，第2点，为什么要在这个位置执行 composer require "eaglewu/swoole-ide-helper=dev-master" ？理论上这里是没有 composer.json 的，也不是一个项目，而且多个项目的上级目录

**Comment by JiankangMai** [comment]
```WEB_ROOT\***```存放了一堆和swoft-framework完全无关的项目，用户可能在此处安装任意其他项目，他们也可能是```WT_ROOT\PROJECT_A```,```WEB_ROOT\PROJECT_B```,swoole-ide-helper只是一个能导致问题的示例。

swoft框架的项目根目录是```\WEB_ROOT\swoft-framework```，一般来说他不应该受```\WEB_ROOT\```下的其他目录的影响。

如果使用composer 安装的swoft-framework一般是不会有这个问题的，因为这时```\WEB_ROOT\```就是,```vendor\swoft```,下面的全是swoft社区的组件。但是如果我通过git clone或其他方式引入swoft -framework，```WEB_ROOT\```就可能没那么干净了，这种情况下有有一定概率swoft-framework运行异常。
